services:
  postgres:
    image: 'postgres:16.2'
    env_file: .env
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 1s
      timeout: 1s
      retries: 60
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  minio:
    image: 'minio/minio:RELEASE.2024-05-28T17-19-04Z'
    env_file: .env
    environment:
      - MC_HOST_custom=http://localhost:${MINIO_API_PORT}
    command: server --console-address ":${MINIO_WEB_PORT}" /data
    ports:
      - ${MINIO_API_PORT}:${MINIO_API_PORT}
      - ${MINIO_WEB_PORT}:${MINIO_WEB_PORT}
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 1s
      timeout: 1s
      retries: 60
    volumes:
      - minio-data:/data
    restart: always
  backend:
    build: backend
    env_file: .env
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: always
  frontend:
    build: frontend
    env_file: .env
    ports:
      - ${REACT_PORT}:${REACT_PORT}
    depends_on:
      backend:
        condition: service_started
    restart: always

volumes:
  postgres-data:
  minio-data:
