# Generated by Django 5.0.4 on 2024-04-23 08:33

import apps.musicians.models
import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicians', '0001_creating_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('genre', models.CharField(max_length=150, verbose_name='genre')),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1440)], verbose_name='duration')),
            ],
            options={
                'verbose_name': 'composition',
                'verbose_name_plural': 'compositions',
                'db_table': '"musicians"."compositions"',
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('birth_date', models.DateField(default=datetime.date.today, validators=[django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='birth date')),
            ],
            options={
                'verbose_name': 'musician',
                'verbose_name_plural': 'musicians',
                'db_table': '"musicians"."musicians"',
            },
        ),
        migrations.CreateModel(
            name='MusicianComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.composition', verbose_name='composition')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.musician', verbose_name='musician')),
            ],
            options={
                'verbose_name': 'relationship musician-composition',
                'verbose_name_plural': 'relationships musician-composition',
                'db_table': '"musicians"."musicians_compositions"',
                'unique_together': {('musician', 'composition')},
            },
        ),
        migrations.AddField(
            model_name='composition',
            name='musicians',
            field=models.ManyToManyField(through='musicians.MusicianComposition', to='musicians.musician', verbose_name='musicians'),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('year', models.PositiveIntegerField(default=apps.musicians.models.current_year, validators=[django.core.validators.MaxValueValidator(apps.musicians.models.current_year)], verbose_name='year')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.musician', verbose_name='musician')),
            ],
            options={
                'verbose_name': 'award',
                'verbose_name_plural': 'awards',
                'db_table': '"musicians"."awards"',
                'unique_together': {('title', 'year')},
            },
        ),
    ]
