# Generated by Django 5.0.4 on 2024-05-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0002_creating_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='audio_file',
            field=models.FileField(default=None, upload_to='', verbose_name='audio file'),
            preserve_default=False,
        ),
    ]
